added the check for response processed, and renamed success to send
ava57r/zbx-sender-rs pull request #1
Opened 2018-06-28 07:59 UTC by Rutger798

2018-06-28 17:29 UTC, ava57r requested changes

2018-06-28 17:29 UTC, andreevlex commented on src/lib.rs
> +    pub fn is_processed(&self) -> bool { self.info.contains("processed: 1") }
Maybe we should do an analysis of all the values, for example [code](https://github.com/andreevlex/zabbix-sender-cs/blame/master/ZabbixSender/SenderResponse.cs#L50), as did for us C#
add
- Processed
- Failed
- Total
- SecondsSpent

2018-06-28 17:29 UTC, andreevlex commented on src/lib.rs
> +    pub fn is_sent(&self) -> bool {
breaking change. Is it necessary to rename?

2018-07-04 15:49 UTC, Rutger798 commented
You have a valid point, so i have reverted the name change, and implemented the other status like you did in C#.

I'am bit new to rust and very new to github so just let me know if a should do something different.

2018-07-09 18:42 UTC, ava57r approved these changes

2018-07-09 18:44 UTC, merged

2018-07-10 08:16 UTC, andreevlex commented
Thanks

2018-07-10 08:28 UTC, Rutger798 commented
Thank you for merging!